# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: OnPrem
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See - task: AzureRmWebAppDeployment@4

-task: Azuredeployemtntowebapp
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'KOMAL_FARZI_MCT (21087fd8-ddac-43ad-9202-7fe47cb92dbb)'
    appType: 'webApp'
    WebAppName: 'devtestcodeapp'
    packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'
  displayName: 'Run a multi-line script'
